server:
    port: 8580
    shutdown: graceful

spring:
    application:
        name: apigateway
        
    cloud:
        gateway:
            routes:
                - id: status-route
                  uri: lb://service1
                  predicates: 
                    - Path=/status
        discovery:
            enabled: true
                    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/         
        healthcheck:
            enabled: true
        registry-fetch-interval-seconds: 10
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    refresh:
      enabled: true      
    shutdown:
      enabled: true
        
    
      
    
    
